### ISSUE TITLE
NullPointerException at runtime on Windows (DFlockers & DCircles)

### ISSUE THREAD

**Issue by Robadob** [isislab-unisa/dmason#2]
Following from the Issue I reported yesterday, I've tried running both the `DFlockers` and `DCircles` models (on Windows) and both have thrown a `NullPointerException` during their `start()` methods.

`it.isislab.dmason.sim.app.DFlockers.DFlockers.start(DFlockers.java:175)`
and
`it.isislab.dmason.sim.app.DCircles.DCircles.start(DCircles.java:133)`

The offending line of code in `DCircles.java` suggests that `circles` is `null`.

`while(circles.size() != super.NUMAGENTS / super.NUMPEERS)`

This would mean that the allocation or `circles` is failing silently (it's allocated above in a `try-catch`), however I'm not familiar enough with your codebase to assume a cause or solution.

I also emailed your     isislab.unisa@gmail address when I first came across this yesterday.

Thanks

P.S. When I build DMason with tests, they also stall without completing, this issue may be related.

**Comment by miccar** [comment]
Probably null pointer exception is caused by your bad partitioning of DMason field. You have to insert a value for AOI smaller than width and smaller than height.
Before run a simulation  test parameters(width, height,aoi) in class test in DFlockers and DCircles packages.You have to download and start Apache ActivemQ, we use 5.7 version, before running a test class; otherwise launch an instance of MasterServerMain(it launch an embedded activemq server) and run a TestClass. If you do not solve with null pointer, please send us the configuration to replicate null pointer (width, height,aoi and number of worker you have selected). 
After last changed in DMason, all junit test classes can cause an error and so the build without skip tests caused problems. For some other issues, please write us under this post or send me a mail at michele.carillo@gmail.com
Thanks

**Comment by Robadob** [comment]
Yes that appears to have solved the null pointer exception, I was able to run both the `DFlockers` and `DCircles` models with uniform partitioning, 2 rows, 2 cols, 1 area of interest.

Could you perhaps clarify the purpose of the 'Area of Interest' parameter?

Additionally is there a 'best' row/col/AOI configuration for executing a model on a single node (with multiple threads)?

**Comment by serfla** [comment]
D-Mason is provided for running simulations in distributed environment, so if your idea is to lunch simulation on a single node, you can do this but for testing, otherwise you should use Mason (the standalone version). To run a test simulation we provide in the same package a class which its name starts with Test, so after running ActiveMQ, you can run the simulation, obviously, the computation load depends from more factors: number of agents, width and height values and partitioning. More agents involves much computation, but for testing simulation a 400x400 field, few agents and a 2x2 partitioning are parameters sufficient for test it.

The AOI value is the range in which each agent can either collect information or interact with other agents. For example at distance 2 (from its position) it can compute the neighbors numbers. So if you make a field 300x300 and a 3x3 partitioning, each tile has 100x100 dimension, so the AOI mustn't exceed both tile sides.
